version: 2.1

orbs:
  win: circleci/windows@2.4.1

parameters:
  run_build:
    default: false
    type: boolean

jobs:
  build:
    executor:
      name: win/default
      size: large
    steps:
    # default shell is Powershell
    - run:
        shell: powershell.exe
        command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
    - run:
        shell: bash.exe
        command: echo hello && echo world
    - run:
        shell: cmd.exe
        command: echo hello & echo world
    - run:
        shell: bash.exe
        command: |
          git clone https://github.com/envoyproxy/envoy.git
    - run:
        shell: bash.exe
        command: |
          pushd envoy
          ./ci/run_envoy_docker.sh ci/windows_ci_steps.sh

workflows:
  version: 2
  build:
    jobs:
    - build
