name: Create Custom VM Image

on:
  workflow_dispatch:

jobs:
  build-envoy-win-2019:
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Create Azure VM
      uses: azure/CLI@v1
      with:
        azcliversion: 2.31.0
        inlineScript: |
          az vm create \
            --name envoy-${GITHUB_SHA::7} \
            --resource-group ${{ secrets.AZURE_ENVOY_BUILD_RESOURCE_GROUP }} \
            --image ${{ secrets.AZURE_ENVOY_BUILD_IMAGE }} \
            --admin-username ${{ secrets.AZURE_ENVOY_ADMIN_USERNAME }} \
            --admin-password ${{ secrets.AZURE_ENVOY_ADMIN_PASSWORD }} \
            --priority Spot \
            --eviction-policy Delete \
            --os-disk-delete-option Delete \
            --nic-delete-option Delete \
            --license-type Windows_Client \
            --size ${{ secrets.AZURE_ENVOY_VM_SIZE }}

    - uses: actions/github-script@v5
      with:
        script: |
          const token = await octokit.rest.actions.createRegistrationTokenForRepo({
            owner: "bartsmykla",
            repo: "envoy-windows-build",
          });
          
          console.log("expires_at", token.expires_at);

    - name: Delete Azure VM
      uses: azure/CLI@v1
      with:
        azcliversion: 2.31.0
        inlineScript: |
          az vm delete \
            --name envoy-${GITHUB_SHA::7} \
            --resource-group ${{ secrets.AZURE_ENVOY_BUILD_RESOURCE_GROUP }} \
            --yes
